A few changes to the shell scripts to start bookies
Author: Franck Cuny <franckcuny@gmail.com>

Reviewers: Sijie Guo <sijie@apache.org>

Closes #43 from franckcuny/fcuny/scripts-start-server

Conflicts:
	bookkeeper-server/bin/bookkeeper

diff --git a/bookkeeper-server/bin/bookkeeper b/bookkeeper-server/bin/bookkeeper
--- a/bookkeeper-server/bin/bookkeeper
+++ b/bookkeeper-server/bin/bookkeeper
@@ -117,56 +117,76 @@ fi
 
 # Check for the java to use
 if [[ -z $JAVA_HOME ]]; then
-    JAVA=$(which java)
-    if [ $? = 0 ]; then
-        echo "JAVA_HOME not set, using java from PATH. ($JAVA)"
-    else
-        echo "Error: JAVA_HOME not set, and no java executable found in $PATH." 1>&2
-        exit 1
-    fi
+  JAVA=$(which java)
+  if [ $? = 0 ]; then
+    echo "JAVA_HOME not set, using java from PATH. ($JAVA)"
+  else
+    echo "Error: JAVA_HOME not set, and no java executable found in $PATH." 1>&2
+    exit 1
+  fi
 else
-    JAVA=$JAVA_HOME/bin/java
+  JAVA=$JAVA_HOME/bin/java
 fi
 
 # exclude tests jar
-RELEASE_JAR=`ls $BK_HOME/bookkeeper-server-*.jar 2> /dev/null | grep -v tests | tail -1` 
-if [ $? == 0 ]; then
-    BOOKIE_JAR=$RELEASE_JAR
+RELEASE_JAR=$(ls ${BK_HOME}/bookkeeper-server-*.jar 2> /dev/null | grep -v tests | tail -1)
+if [ -n "${RELEASE_JAR}" ]; then
+  BOOKIE_JAR=$RELEASE_JAR
 fi
 
 # exclude tests jar
-BUILT_JAR=`ls $BK_HOME/target/bookkeeper-server-*.jar 2> /dev/null | grep -v tests | tail -1`
-if [ $? != 0 ] && [ ! -e "$BOOKIE_JAR" ]; then 
-    echo "\nCouldn't find bookkeeper jar.";
-    echo "Make sure you've run 'mvn package'\n";
-    exit 1;
-elif [ -e "$BUILT_JAR" ]; then
+BUILT_JAR=$(ls ${BK_HOME}/target/bookkeeper-server-*.jar 2> /dev/null | grep -v tests | tail -1)
+
+if [ -z "${BUILT_JAR}" ] && [ -z "${BOOKIE_JAR}" ]; then
+  echo "Couldn't find bookkeeper jar."
+  read -p "Do you want me to run \`mvn package -DskiptTests\` for you ? " answer
+  case "${answer:0:1}" in
+    y|Y )
+      mvn package -DskipTests
+      ;;
+    * )
+      exit 1
+      ;;
+  esac
+
+  BUILT_JAR=$(ls ${BK_HOME}/target/bookkeeper-server-*.jar 2> /dev/null | grep -v tests | tail -1)
+  if [ -n "${BUILT_JAR}" ]; then
     BOOKIE_JAR=$BUILT_JAR
+  fi
+fi
+
+if [ -e "${BUILT_JAR}" ]; then
+  BOOKIE_JAR="${BUILT_JAR}"
+fi
+
+if [ ! -e "${BOOKIE_JAR}" ]; then
+  echo "Could not find bookkeeper jar."
+  exit 1
 fi
 
 add_maven_deps_to_classpath() {
-    MVN="mvn"
-    if [ "$MAVEN_HOME" != "" ]; then
-	MVN=${MAVEN_HOME}/bin/mvn
-    fi
-    
-    # Need to generate classpath from maven pom. This is costly so generate it
-    # and cache it. Save the file into our target dir so a mvn clean will get
-    # clean it up and force us create a new one.
-    f="${BK_HOME}/target/cached_classpath.txt"
-    if [ ! -f "${f}" ]
-    then
-	${MVN} -f "${BK_HOME}/pom.xml" dependency:build-classpath -Dmdep.outputFile="${f}" &> /dev/null
-    fi
-    BOOKIE_CLASSPATH=${CLASSPATH}:`cat "${f}"`
+  MVN="mvn"
+  if [ "$MAVEN_HOME" != "" ]; then
+    MVN=${MAVEN_HOME}/bin/mvn
+  fi
+
+  # Need to generate classpath from maven pom. This is costly so generate it
+  # and cache it. Save the file into our target dir so a mvn clean will get
+  # clean it up and force us create a new one.
+  f="${BK_HOME}/target/cached_classpath.txt"
+  if [ ! -f "${f}" ]
+  then
+    ${MVN} -f "${BK_HOME}/pom.xml" dependency:build-classpath -Dmdep.outputFile="${f}" &> /dev/null
+  fi
+  BOOKIE_CLASSPATH=${CLASSPATH}:`cat "${f}"`
 }
 
 if [ -d "$BK_HOME/lib" ]; then
-    for i in $BK_HOME/lib/*.jar; do
-	BOOKIE_CLASSPATH=$BOOKIE_CLASSPATH:$i
-    done
+  for i in $BK_HOME/lib/*.jar; do
+    BOOKIE_CLASSPATH=$BOOKIE_CLASSPATH:$i
+  done
 else
-    add_maven_deps_to_classpath
+  add_maven_deps_to_classpath
 fi
 
 if [ $COMMAND == "shell" ]; then
@@ -210,11 +230,11 @@ if [ $COMMAND == "jmx" ]; then
 fi
 
 if [ -z "$BOOKIE_CONF" ]; then
-    BOOKIE_CONF=$DEFAULT_CONF
+  BOOKIE_CONF=$DEFAULT_CONF
 fi
 
 if [ -z "$BOOKIE_LOG_CONF" ]; then
-    BOOKIE_LOG_CONF=$DEFAULT_LOG_CONF
+  BOOKIE_LOG_CONF=$DEFAULT_LOG_CONF
 fi
 
 BOOKIE_LOG_FORMAT=${BOOKIE_LOG_FORMAT:-"$HOSTNAME.sfstore"}
@@ -269,15 +289,15 @@ OPTS="$OPTS -Dbookkeeper.log.filecount=$BOOKIE_LOG_FILE_COUNT"
 #Change to BK_HOME to support relative paths
 cd "$BK_HOME"
 if [ $COMMAND == "bookie" ]; then
-    exec $JAVA $OPTS $JMX_ARGS org.apache.bookkeeper.proto.BookieServer --conf $BOOKIE_CONF $@
+  exec $JAVA $OPTS $JMX_ARGS org.apache.bookkeeper.proto.BookieServer --conf $BOOKIE_CONF $@
 elif [ $COMMAND == "autorecovery" ]; then
     exec $JAVA $OPTS org.apache.bookkeeper.replication.AutoRecoveryMain --conf $BOOKIE_CONF $@
 elif [ $COMMAND == "localbookie" ]; then
-    NUMBER=$1
-    shift
-    exec $JAVA $OPTS $JMX_ARGS org.apache.bookkeeper.util.LocalBookKeeper $NUMBER $BOOKIE_CONF $@
+  NUMBER=$1
+  shift
+  exec $JAVA $OPTS $JMX_ARGS org.apache.bookkeeper.util.LocalBookKeeper $NUMBER $BOOKIE_CONF $@
 elif [ $COMMAND == "upgrade" ]; then
-    exec $JAVA $OPTS org.apache.bookkeeper.bookie.FileSystemUpgrade --conf $BOOKIE_CONF $@
+  exec $JAVA $OPTS org.apache.bookkeeper.bookie.FileSystemUpgrade --conf $BOOKIE_CONF $@
 elif [ $COMMAND == "shell" ]; then
     ENTRY_FORMATTER_ARG="-DentryFormatterClass=${ENTRY_FORMATTER_CLASS:-org.apache.bookkeeper.util.HexDumpEntryFormatter}"
     LEDGERID_FORMATTER_ARG="-DledgerIdFormatterClass=${LEDGERID_FORMATTER_CLASS:-org.apache.bookkeeper.util.LedgerIdFormatter\$LongLedgerIdFormatter}"
@@ -333,7 +353,7 @@ elif [ $COMMAND == "jmx" ]; then
         jmx_help
     fi
 else
-    exec $JAVA $OPTS $COMMAND $@
+  exec $JAVA $OPTS $COMMAND $@
 fi
 
 
