(@bug W-3256987@) CLI for JMX Operations
Shell command line interface for JMX operations
using JMXTerm client library.

JMX Remote Monitoring/Management is enabled for
'bookie' and 'localbookie' options.

Removed 'JMXLOCALONLY' and 'JMXDISABLE' from
bookkeeper shell script, which are not required
considering we are using Java1.8 and JMX is enabled
by default (local monitoring/management).

diff --git a/bookkeeper-server/bin/bookkeeper b/bookkeeper-server/bin/bookkeeper
--- a/bookkeeper-server/bin/bookkeeper
+++ b/bookkeeper-server/bin/bookkeeper
@@ -29,26 +29,6 @@ then
   exit 1
 fi
 
-# See the following page for extensive details on setting
-# up the JVM to accept JMX remote management:
-# http://java.sun.com/javase/6/docs/technotes/guides/management/agent.html
-# by default we allow local JMX connections
-if [ "x$JMXLOCALONLY" = "x" ]
-then
-    JMXLOCALONLY=false
-fi
-
-if [ "x$JMXDISABLE" = "x" ]
-then
-    echo "JMX enabled by default" >&2
-    # for some reason these two options are necessary on jdk6 on Ubuntu
-    #   accord to the docs they are not necessary, but otw jconsole cannot
-    #   do a local attach
-    JMX_ARGS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.local.only=$JMXLOCALONLY"
-else
-    echo "JMX disabled by user request" >&2
-fi
-
 BINDIR=`dirname "$0"`
 BK_HOME=`cd $BINDIR/..;pwd`
 
@@ -58,6 +38,11 @@ DEFAULT_LOG_CONF=$BK_HOME/conf/log4j.properties
 DEFAULT_LOCALBOOKIES_CONFIG_DIR=/tmp/localbookies-config
 
 source $BK_HOME/conf/bkenv.sh
+
+if [ "x$JMX_PORT_NUM" != "x" ]
+then
+    JMX_ARGS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=$JMX_PORT_NUM -Dcom.sun.management.jmxremote.local.only=true -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false"
+fi
 
 # Check for the java to use
 if [[ -z $JAVA_HOME ]]; then
@@ -92,12 +77,13 @@ bookkeeper_help() {
     cat <<EOF
 Usage: bookkeeper <command>
 where command is one of:
-    bookie              Run a bookie server
-    autorecovery        Run AutoRecovery service daemon
-    localbookie <n>     Run a test ensemble of <n> bookies locally
-    upgrade             Upgrade bookie filesystem
-    shell               Run shell for admin commands
-    help                This help message
+    bookie              								Run a bookie server
+    autorecovery        								Run AutoRecovery service daemon
+    localbookie <n>     								Run a test ensemble of <n> bookies locally
+    upgrade             								Upgrade bookie filesystem
+    shell [localbookie -<localbookieAddress>] [ledgeridformat -<hex/long/uuid>]		Run shell for admin commands
+    jmx [localbookie -<localbookieAddress>]						Run jmx operations
+    help                								This help message
 
 or command is the full name of a class with a defined main() method.
 
@@ -112,6 +98,25 @@ Environment variables:
    BOOKIE_STOP_TIMEOUT    Wait time before forcefully kill the Bookie server instance, if the stop is not successful
 
 These variable can also be set in conf/bkenv.sh
+EOF
+}
+
+jmx_help() {
+    cat <<EOF
+Usage: bookkeeper jmx [localbookie -<localbookieAddress>] <command>
+where command is one of:
+    forcecompaction
+    suspendmajorgc
+    suspendminorgc
+    resumeminorgc
+    resumemajorgc
+    flushbookie
+    openfilelimit
+    pagelimit
+    pagesize
+    pagecount
+    numopenledgers
+    help
 EOF
 }
 
@@ -183,6 +188,13 @@ if [ $COMMAND == "shell" ]; then
     fi
 fi
 
+if [ $COMMAND == "jmx" ]; then
+    if [[ $1 == "localbookie" ]]; then
+        BOOKIE_CONF=$DEFAULT_LOCALBOOKIES_CONFIG_DIR/${2:1}.conf
+        shift 2
+    fi
+fi
+
 if [ -z "$BOOKIE_CONF" ]; then
     BOOKIE_CONF=$DEFAULT_CONF
 fi
@@ -228,7 +240,7 @@ cd "$BK_HOME"
 if [ $COMMAND == "bookie" ]; then
     exec $JAVA $OPTS $JMX_ARGS org.apache.bookkeeper.proto.BookieServer --conf $BOOKIE_CONF $@
 elif [ $COMMAND == "autorecovery" ]; then
-    exec $JAVA $OPTS $JMX_ARGS org.apache.bookkeeper.replication.AutoRecoveryMain --conf $BOOKIE_CONF $@
+    exec $JAVA $OPTS org.apache.bookkeeper.replication.AutoRecoveryMain --conf $BOOKIE_CONF $@
 elif [ $COMMAND == "localbookie" ]; then
     NUMBER=$1
     shift
@@ -241,7 +253,58 @@ elif [ $COMMAND == "shell" ]; then
     exec $JAVA ${OPTS/-XX:+PrintStringTableStatistics/} $ENTRY_FORMATTER_ARG $LEDGERID_FORMATTER_ARG org.apache.bookkeeper.bookie.BookieShell -conf $BOOKIE_CONF $@
 elif [ $COMMAND == "help" ]; then
     bookkeeper_help;
+elif [ $COMMAND == "jmx" ]; then
+    getPortNum() {
+        while read line; do
+            trimmedline=`echo $line | tr -d ' '`
+            if [[ $trimmedline == bookiePort=* ]]; then
+                PORT_NUM=${trimmedline/#bookiePort=/}
+                break
+            fi
+        done < $BOOKIE_CONF
+    }
+    getPortNum
+    if [[ -z "$PORT_NUM" ]]; then
+        echo "Something went wrong, bookiePort is not found in BookieConfig file: $BOOKIE_CONF"
+        exit 1
+    fi
+# get JMX command
+    JMX_COMMAND=$1
+    JMX_EXECUTION_COMMAND="exec $JAVA -jar $BK_HOME/bin/jmxterm-1.0-alpha-4-uber.jar -l localhost:$JMX_PORT_NUM -n"
+    if [[ -z "$JMX_COMMAND" ]]; then
+        jmx_help;
+    elif [ $JMX_COMMAND == "forcecompaction" ]; then
+        echo "bean org.apache.BookKeeperService:name0=BookieServer_$PORT_NUM,name1=Bookie,name2=Compaction-GarbageCollector"$'\n'"run forceCompaction"$'\n'"bye" | $JMX_EXECUTION_COMMAND
+    elif [ $JMX_COMMAND == "suspendmajorgc" ]; then
+        echo "bean org.apache.BookKeeperService:name0=BookieServer_$PORT_NUM,name1=Bookie,name2=Compaction-GarbageCollector"$'\n'"run suspendMajorGC"$'\n'"bye" | $JMX_EXECUTION_COMMAND
+    elif [ $JMX_COMMAND == "suspendminorgc" ]; then
+        echo "bean org.apache.BookKeeperService:name0=BookieServer_$PORT_NUM,name1=Bookie,name2=Compaction-GarbageCollector"$'\n'"run suspendMinorGC"$'\n'"bye" | $JMX_EXECUTION_COMMAND
+    elif [ $JMX_COMMAND == "resumeminorgc" ]; then
+        echo "bean org.apache.BookKeeperService:name0=BookieServer_$PORT_NUM,name1=Bookie,name2=Compaction-GarbageCollector"$'\n'"run resumeMinorGC"$'\n'"bye" | $JMX_EXECUTION_COMMAND
+    elif [ $JMX_COMMAND == "resumemajorgc" ]; then
+        echo "bean org.apache.BookKeeperService:name0=BookieServer_$PORT_NUM,name1=Bookie,name2=Compaction-GarbageCollector"$'\n'"run resumeMajorGC"$'\n'"bye" | $JMX_EXECUTION_COMMAND
+    elif [ $JMX_COMMAND == "flushbookie" ]; then
+        echo "bean org.apache.BookKeeperService:name0=BookieServer_$PORT_NUM,name1=Bookie,name2=SyncThread"$'\n'"run flushBookie"$'\n'"bye" | $JMX_EXECUTION_COMMAND
+    elif [ $JMX_COMMAND == "openfilelimit" ]; then
+        echo "bean org.apache.BookKeeperService:name0=BookieServer_$PORT_NUM,name1=Bookie,name2=LedgerCache"$'\n'"get OpenFileLimit"$'\n'"bye" | $JMX_EXECUTION_COMMAND
+    elif [ $JMX_COMMAND == "pagelimit" ]; then
+        echo "bean org.apache.BookKeeperService:name0=BookieServer_$PORT_NUM,name1=Bookie,name2=LedgerCache"$'\n'"get PageLimit"$'\n'"bye" | $JMX_EXECUTION_COMMAND
+    elif [ $JMX_COMMAND == "pagesize" ]; then
+        echo "bean org.apache.BookKeeperService:name0=BookieServer_$PORT_NUM,name1=Bookie,name2=LedgerCache"$'\n'"get PageSize"$'\n'"bye" | $JMX_EXECUTION_COMMAND
+    elif [ $JMX_COMMAND == "pagecount" ]; then
+        echo "bean org.apache.BookKeeperService:name0=BookieServer_$PORT_NUM,name1=Bookie,name2=LedgerCache"$'\n'"get PageCount"$'\n'"bye" | $JMX_EXECUTION_COMMAND
+    elif [ $JMX_COMMAND == "numopenledgers" ]; then
+        echo "bean org.apache.BookKeeperService:name0=BookieServer_$PORT_NUM,name1=Bookie,name2=LedgerCache"$'\n'"get NumOpenLedgers"$'\n'"bye" | $JMX_EXECUTION_COMMAND
+    elif [ $JMX_COMMAND == "help" ]; then
+        jmx_help;
+    else
+        echo "Unknown JMX Command: $JMX_COMMAND"
+    fi
 else
     exec $JAVA $OPTS $COMMAND $@
 fi
+
+
+
+
 
